# frozen_string_literal: true
#
# Generated by sapphire-compiler. Do not edit by hand.
# See docs/build/02-source-and-output-layout.md for the output contract.

require 'sapphire/prelude'

module Sapphire
  class Main

    def self.main
      Sapphire::Prelude.monad_then(((Sapphire::Main.greet).call("Sapphire")), ((Sapphire::Main.greet).call("world")))
    end

    def self.greet
      ->(_arg0) { (name = _arg0; (Sapphire::Main.rubyPuts).call((Sapphire::Main.makeMessage).call(name))) }
    end

    def self.makeMessage
      ->(_arg0) { (name = _arg0; (("Hello, ") + (((name) + ("!"))))) }
    end

    def self.rubyPuts
      ->(s) {
          Sapphire::Runtime::Ruby.prim_embed do
            puts s
            {}
          end
        }
    end

    # Entry helper — `sapphire run` dispatches here.
    def self.run_main
      result = Sapphire::Prelude.run_action(main)
      case result[:tag]
      when :Ok
        0
      when :Err
        err = result[:values][0]
        klass = err[:values][0]
        msg   = err[:values][1]
        bt    = err[:values][2]
        warn "[sapphire run] #{klass}: #{msg}"
        bt.each { |line| warn "  #{line}" }
        1
      end
    end
  end
end
