# Generated by sapphire-compiler; do not edit.
#
# This file is the Ruby-side realisation of the spec-09 prelude plus
# the runtime helpers that `docs/impl/24-codegen-expr.md`,
# `docs/impl/25-codegen-adt-record.md`, and
# `docs/impl/26-codegen-effect-monad.md` call into from generated
# module code. It is re-emitted on every `sapphire build` — the
# runtime gem (R1 through R5) deliberately ships nothing from this
# layer, per CLAUDE.md's "runtime stays small, prelude is codegen
# surface" split.

require 'sapphire/runtime'

module Sapphire
  class Prelude
    # ---- Constants: Bool / Ordering -------------------------------

    # Spec 10 §Ground types: Bool maps to Ruby true/false.
    True  = true
    False = false

    # Spec 10 §Ordering: bare Ruby symbols, NOT tagged hashes.
    LT = :lt
    EQ = :eq
    GT = :gt

    # ---- ADT constructors (Maybe / Result / List) -----------------
    #
    # List uses the Ruby Array representation per spec 10 §Lists,
    # so Nil / Cons do NOT go through ADT.make; they produce Arrays
    # directly.

    Sapphire::Runtime::ADT.define_variants(
      self,
      [[:Nothing, 0], [:Just, 1], [:Err, 1], [:Ok, 1]]
    )

    def self.Nil
      SP_NIL
    end

    def self.Cons
      SP_CONS
    end

    SP_NIL  = [].freeze
    SP_CONS = ->(x) { ->(xs) { [x, *xs] } }

    # ---- Curried operator helpers ---------------------------------
    #
    # These are only used when an operator is referenced as a value
    # (e.g. `(+)` passed to a higher-order function). BinOp sites are
    # inlined directly by codegen for speed.

    OP_PLUS  = ->(a) { ->(b) { a + b } }
    OP_MINUS = ->(a) { ->(b) { a - b } }
    OP_TIMES = ->(a) { ->(b) { a * b } }
    OP_DIV   = ->(a) { ->(b) { a / b } }
    OP_MOD   = ->(a) { ->(b) { a % b } }
    OP_EQ    = ->(a) { ->(b) { a == b } }
    OP_NEQ   = ->(a) { ->(b) { a != b } }
    OP_LT    = ->(a) { ->(b) { a < b } }
    OP_LE    = ->(a) { ->(b) { a <= b } }
    OP_GT    = ->(a) { ->(b) { a > b } }
    OP_GE    = ->(a) { ->(b) { a >= b } }
    OP_AND   = ->(a) { ->(b) { a && b } }
    OP_OR    = ->(a) { ->(b) { a || b } }
    OP_CONCAT = ->(a) { ->(b) { a + b } }

    # ---- Monad dispatch ------------------------------------------
    #
    # Shape-driven dispatch: we pick the right bind / then semantics
    # from the LHS value. This is the pragmatic alternative to
    # dictionary passing for the M9 scope.

    def self.monad_bind(m, k)
      if m.is_a?(Sapphire::Runtime::Ruby::Action)
        Sapphire::Runtime::Ruby.prim_bind(m) { |x| k.call(x) }
      elsif m.is_a?(Hash) && m.key?(:tag) && m.key?(:values)
        case m[:tag]
        when :Ok
          k.call(m[:values][0])
        when :Err
          m
        when :Just
          k.call(m[:values][0])
        when :Nothing
          m
        else
          raise Sapphire::Runtime::Errors::BoundaryError,
                "monad_bind: unsupported ADT tag #{m[:tag].inspect}"
        end
      elsif m.is_a?(Array)
        m.flat_map { |x| k.call(x) }
      else
        raise Sapphire::Runtime::Errors::BoundaryError,
              "monad_bind: cannot dispatch on #{m.inspect}"
      end
    end

    # `m >> n` — sequential composition that discards the result of
    # `m`. Codegen always wraps `n` in a zero-arg thunk (a `-> { ... }`
    # lambda) so that short-circuiting monads (`Err _`, `Nothing`)
    # never force `n`. The `monad_then` contract is therefore: the
    # second argument is always callable with no arguments and the
    # thunk is forced only when the LHS admits continuation.
    def self.monad_then(m, thunk)
      monad_bind(m, ->(_) { thunk.call })
    end

    # ---- pure fall-back ------------------------------------------
    #
    # Codegen usually specialises `pure` per binding from the
    # return-type head. When the head is unknown, it emits a call
    # here and we raise.

    def self.pure_polymorphic(_x)
      raise Sapphire::Runtime::Errors::BoundaryError,
            "pure_polymorphic: codegen could not specialise this call. " \
            "Annotate the binding's return type."
    end

    # ---- `show` runtime dispatch ---------------------------------
    #
    # Spec 09 §Class instances: Show Int / Show String / Show Bool /
    # Show Ordering / Show (Maybe a) / Show (Result e a) / Show (List a).

    SHOW = ->(x) { show_impl(x) }

    def self.show_impl(x)
      case x
      when Integer
        x.to_s
      when String
        x.dump
      when true
        'True'
      when false
        'False'
      when :lt, :eq, :gt
        { lt: 'LT', eq: 'EQ', gt: 'GT' }[x]
      when Array
        "[#{x.map { |e| show_impl(e) }.join(', ')}]"
      when Hash
        if x.key?(:tag) && x.key?(:values)
          tag = x[:tag]
          vals = x[:values]
          if vals.empty?
            tag.to_s
          else
            "#{tag} #{vals.map { |v| show_impl(v) }.join(' ')}"
          end
        else
          inner = x.map { |k, v| "#{k} = #{show_impl(v)}" }.join(', ')
          "{ #{inner} }"
        end
      else
        x.to_s
      end
    end

    # ---- Utilities (spec 09) -------------------------------------

    ID     = ->(x) { x }
    CONST  = ->(x) { ->(_) { x } }
    FLIP   = ->(f) { ->(a) { ->(b) { f.call(b).call(a) } } }
    COMPOSE = ->(g) { ->(f) { ->(x) { g.call(f.call(x)) } } }

    NEGATE = ->(a) { -a }
    NOT    = ->(a) { !a }

    # List utilities implemented in Ruby on Arrays.

    MAP = ->(f) {
      ->(xs) { xs.map { |x| f.call(x) } }
    }

    FILTER = ->(f) {
      ->(xs) { xs.select { |x| f.call(x) } }
    }

    FOLDR = ->(f) {
      ->(acc) {
        ->(xs) {
          res = acc
          xs.reverse_each { |x| res = f.call(x).call(res) }
          res
        }
      }
    }

    FOLDL = ->(f) {
      ->(acc) {
        ->(xs) {
          res = acc
          xs.each { |x| res = f.call(res).call(x) }
          res
        }
      }
    }

    CONCAT = ->(xss) { xss.flatten(1) }
    CONCAT_MAP = ->(f) {
      ->(xs) { xs.flat_map { |x| f.call(x) } }
    }
    LENGTH = ->(xs) { xs.length }
    HEAD   = ->(xs) {
      xs.empty? ? Sapphire::Runtime::ADT.make(:Nothing, []) : Sapphire::Runtime::ADT.make(:Just, [xs.first])
    }
    TAIL   = ->(xs) {
      xs.empty? ? Sapphire::Runtime::ADT.make(:Nothing, []) : Sapphire::Runtime::ADT.make(:Just, [xs[1..]])
    }
    NULL = ->(xs) { xs.empty? }

    FST = ->(r) { r[:fst] }
    SND = ->(r) { r[:snd] }

    MAYBE = ->(default_) {
      ->(f) {
        ->(m) {
          if m[:tag] == :Nothing
            default_
          else
            f.call(m[:values][0])
          end
        }
      }
    }

    FROM_MAYBE = ->(default_) {
      ->(m) {
        if m[:tag] == :Nothing
          default_
        else
          m[:values][0]
        end
      }
    }

    RESULT = ->(on_err) {
      ->(on_ok) {
        ->(r) {
          if r[:tag] == :Err
            on_err.call(r[:values][0])
          else
            on_ok.call(r[:values][0])
          end
        }
      }
    }

    MAP_ERR = ->(f) {
      ->(r) {
        if r[:tag] == :Err
          Sapphire::Runtime::ADT.make(:Err, [f.call(r[:values][0])])
        else
          r
        end
      }
    }

    READ_INT = ->(s) {
      # Spec 09 §readInt: parse a decimal integer or return Nothing.
      # Accepts a leading minus sign and plain digits.
      if s.is_a?(String) && /\A-?\d+\z/.match?(s)
        Sapphire::Runtime::ADT.make(:Just, [Integer(s, 10)])
      else
        Sapphire::Runtime::ADT.make(:Nothing, [])
      end
    }

    COMPARE = ->(a) {
      ->(b) {
        if a < b
          :lt
        elsif a == b
          :eq
        else
          :gt
        end
      }
    }

    # Monad utilities routed through shape dispatch.

    JOIN = ->(m) { monad_bind(m, ID) }
    WHEN = ->(cond) {
      ->(action) {
        cond ? action : pure_unit_for(action)
      }
    }
    UNLESS = ->(cond) {
      ->(action) {
        cond ? pure_unit_for(action) : action
      }
    }

    def self.pure_unit_for(action)
      # Return a pure action matching the shape of `action`. Used by
      # when/unless to short-circuit while staying in the right monad.
      if action.is_a?(Sapphire::Runtime::Ruby::Action)
        Sapphire::Runtime::Ruby.prim_return({})
      elsif action.is_a?(Hash) && action.key?(:tag)
        case action[:tag]
        when :Ok, :Err
          Sapphire::Runtime::ADT.make(:Ok, [{}])
        when :Just, :Nothing
          Sapphire::Runtime::ADT.make(:Just, [{}])
        else
          Sapphire::Runtime::ADT.make(:Ok, [{}])
        end
      else
        [{}]
      end
    end

    # ---- run helper (I-OQ40 wrapping) ----------------------------
    #
    # runtime.rb returns `[:ok, v] | [:err, e]` 2-tuples. Codegen
    # wraps that into the spec-11 `Result RubyError a` shape here.

    def self.run_action(action)
      tuple = Sapphire::Runtime::Ruby.run(action)
      case tuple
      in [:ok, v]
        Sapphire::Runtime::ADT.make(:Ok, [v])
      in [:err, e]
        Sapphire::Runtime::ADT.make(:Err, [e])
      end
    end

    PRINT = ->(x) {
      Sapphire::Runtime::Ruby.prim_embed { puts show_impl(x) }
    }
  end
end
