//! Sapphire expression → Ruby expression translation.
//!
//! This module is single-shot and stateless per expression: every
//! call to [`render_expr`] produces a Ruby *expression* string (no
//! surrounding statements). Statement-level wrapping (e.g. turning a
//! top-level binding's body into a `def self.name` block) is handled
//! in `decl.rs`.
//!
//! The renderer takes an [`ExprCtx`] carrying the current module's
//! resolver references plus the head type-constructor of the
//! enclosing top-level binding (used to specialise `pure` / `return`
//! per `docs/impl/26-codegen-effect-monad.md`).

use sapphire_core::ast::{CaseArm, DoStmt, Expr, Literal, Pattern};
use sapphire_core::span::Span;
use std::collections::HashMap;

use crate::resolver::{Resolution, ResolvedModule};

use super::emit::escape_ruby_string;
use super::pattern::render_pattern;
use super::runtime;

/// Shared read-only state while rendering an expression tree.
pub struct ExprCtx<'a> {
    pub module: &'a ResolvedModule,
    /// Head type-constructor of the enclosing binding's return type
    /// (e.g. `Some("Ruby")` or `Some("Result")`). Used to specialise
    /// `pure` / `return` calls. `None` means "no type info available";
    /// the specialised-pure helper then falls back to the polymorphic
    /// stub per `docs/impl/26-codegen-effect-monad.md`.
    pub return_head: Option<&'a str>,
    /// Local names currently in scope. Kept to detect locals even when
    /// the resolver's reference table does not carry a span for every
    /// synthesised node (e.g. lambdas generated by do-desugar).
    pub locals: HashMap<String, ()>,
}

impl<'a> ExprCtx<'a> {
    pub fn new(module: &'a ResolvedModule, return_head: Option<&'a str>) -> Self {
        Self {
            module,
            return_head,
            locals: HashMap::new(),
        }
    }

    pub fn with_local(&self, name: &str) -> Self {
        let mut locals = self.locals.clone();
        locals.insert(name.to_string(), ());
        Self {
            module: self.module,
            return_head: self.return_head,
            locals,
        }
    }

    pub fn with_locals<I: IntoIterator<Item = String>>(&self, names: I) -> Self {
        let mut locals = self.locals.clone();
        for n in names {
            locals.insert(n, ());
        }
        Self {
            module: self.module,
            return_head: self.return_head,
            locals,
        }
    }

    /// Convenience for callers holding a slice of names.
    pub fn with_locals_slice(&self, names: &[String]) -> Self {
        self.with_locals(names.iter().cloned())
    }

    fn is_local(&self, span: Span, name: &str) -> bool {
        if self.locals.contains_key(name) {
            return true;
        }
        matches!(
            self.module.references.get(&span),
            Some(Resolution::Local { .. })
        )
    }
}

/// Render a Sapphire expression as a Ruby expression string (no
/// trailing newline, no enclosing parentheses unless required for
/// grouping).
pub fn render_expr(expr: &Expr, ctx: &ExprCtx) -> String {
    match expr {
        Expr::Lit(Literal::Int(i), _) => format!("{i}"),
        Expr::Lit(Literal::Str(s), _) => format!("\"{}\"", escape_ruby_string(s)),

        Expr::Var { name, span, .. } => render_var(name, *span, ctx),

        Expr::OpRef { symbol, .. } => {
            runtime::prelude_value(symbol).unwrap_or_else(|| format!("Sapphire::Prelude::{symbol}"))
        }

        Expr::App { func, arg, .. } => render_app(func, arg, ctx),

        Expr::Lambda { params, body, .. } => render_lambda(params, body, ctx),

        Expr::Let {
            name, value, body, ..
        } => render_let(name, value, body, ctx),

        Expr::If {
            cond,
            then_branch,
            else_branch,
            ..
        } => format!(
            "({} ? ({}) : ({}))",
            render_expr(cond, ctx),
            render_expr(then_branch, ctx),
            render_expr(else_branch, ctx)
        ),

        Expr::Case {
            scrutinee, arms, ..
        } => render_case(scrutinee, arms, ctx),

        Expr::BinOp {
            op, left, right, ..
        } => render_binop(op, left, right, ctx),

        Expr::Neg { value, .. } => format!("(-({}))", render_expr(value, ctx)),

        Expr::RecordLit { fields, .. } => {
            let parts: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{k}: ({})", render_expr(v, ctx)))
                .collect();
            format!("{{ {} }}", parts.join(", "))
        }

        Expr::RecordUpdate { record, fields, .. } => {
            let parts: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{k}: ({})", render_expr(v, ctx)))
                .collect();
            format!("({}).merge({})", render_expr(record, ctx), parts.join(", "))
        }

        Expr::FieldAccess { record, field, .. } => {
            format!("({})[:{}]", render_expr(record, ctx), field)
        }

        Expr::ListLit { items, .. } => {
            let parts: Vec<String> = items.iter().map(|e| render_expr(e, ctx)).collect();
            format!("[{}]", parts.join(", "))
        }

        Expr::Do { stmts, .. } => render_do(stmts, ctx),
    }
}

fn render_var(name: &str, span: Span, ctx: &ExprCtx) -> String {
    // Locals shadow prelude. Resolver's reference table is the
    // authoritative source but we also honour the ExprCtx local set
    // for synthesised lambdas.
    if ctx.is_local(span, name) {
        return name.to_string();
    }

    // Handle upper-case constructor references specially: a reference
    // that is not in a function-application context needs to return a
    // curried constructor (or the bare value for nullary ones).
    if is_upper(name) {
        if let Some(rendered) = runtime::prelude_value(name) {
            return rendered;
        }
        // User-defined ADT constructor; emit via ADT.make. Arity
        // isn't trivially available here without threading the
        // typeck env, so we emit a curried helper. The pattern of
        // `App (Var Ctor) args` is detected in `render_app`, so
        // reaching here means value position.
        //
        // For M9 this path is not exercised by user-defined ADTs
        // with arguments except through HttpError data constructors
        // in example 4, which are applied to arguments (so they go
        // through render_app).
        return format!("->(x) {{ Sapphire::Runtime::ADT.make(:{name}, [x]) }}");
    }

    // Lowercase name — a value reference. Prelude first, then
    // module-level binding.
    if let Some(rendered) = runtime::prelude_value(name) {
        // Special-case pure/return specialisation is handled in
        // render_app when the reference appears in call position;
        // in value position the polymorphic stub is fine.
        return rendered;
    }
    if let Some(Resolution::Global(r)) = ctx.module.references.get(&span) {
        return format!(
            "{}.{}",
            ruby_module_path(&r.module.segments),
            super::emit::value_ident(&r.name)
        );
    }
    // Not resolved as prelude or global — fall back to the bare name
    // (treat as local).
    name.to_string()
}

fn render_app(func: &Expr, arg: &Expr, ctx: &ExprCtx) -> String {
    // Detect constructor application: `Just x`, `Ok x`, `Cons h t`,
    // `HttpError ...`. Walk the left spine to collect all arguments
    // applied to a constructor reference.
    if let Some((ctor_name, args)) = collect_ctor_app(func, arg) {
        return render_ctor_call(&ctor_name, &args, ctx);
    }

    // Detect `pure x` / `return x` that can be specialised. We must
    // not rewrite a user-bound `pure` / `return` local (e.g. a
    // function parameter shadowing the prelude), so the outer guard
    // is `!is_local`; the remaining decision is whether the reference
    // resolved to `Prelude.pure` / `Prelude.return` or to something
    // else entirely (a user binding in another module with the same
    // name — unusual but legal). In the "something else entirely"
    // case we fall through to the ordinary curried call below rather
    // than substitute a specialised form.
    if let Expr::Var { name, span, .. } = func {
        if (name == "pure" || name == "return") && !ctx.is_local(*span, name) {
            let resolves_to_prelude = matches!(
                ctx.module.references.get(span),
                Some(Resolution::Global(r))
                    if r.module.segments.len() == 1 && r.module.segments[0] == "Prelude"
            );
            // When the reference table is missing this span (rare —
            // only for synthesised nodes like do-desugar lambdas that
            // reach here through variable renames), we still want to
            // specialise, since nothing else can legitimately own a
            // non-local `pure` / `return` without going through the
            // prelude.
            let has_no_resolution = !ctx.module.references.contains_key(span);
            if resolves_to_prelude || has_no_resolution {
                let template = runtime::specialised_pure(ctx.return_head);
                let arg_src = render_expr(arg, ctx);
                return template.replace("{}", &arg_src);
            }
        }
    }

    format!(
        "({}).call({})",
        render_expr(func, ctx),
        render_expr(arg, ctx)
    )
}

fn render_ctor_call(name: &str, args: &[&Expr], ctx: &ExprCtx) -> String {
    // Special cases from spec 10.
    match name {
        "True" => return "true".into(),
        "False" => return "false".into(),
        "LT" => return ":lt".into(),
        "EQ" => return ":eq".into(),
        "GT" => return ":gt".into(),
        "Nil" => return "[]".into(),
        "Cons" if args.len() == 2 => {
            return format!(
                "[{}, *{}]",
                render_expr(args[0], ctx),
                render_expr(args[1], ctx)
            );
        }
        _ => {}
    }
    let arg_exprs: Vec<String> = args.iter().map(|e| render_expr(e, ctx)).collect();
    format!(
        "Sapphire::Runtime::ADT.make(:{name}, [{}])",
        arg_exprs.join(", ")
    )
}

/// If `f x` — with potentially more left-spine applications — targets
/// an upper-case constructor, return `(ctor_name, args)`. Otherwise
/// return `None`.
fn collect_ctor_app<'a>(func: &'a Expr, arg: &'a Expr) -> Option<(String, Vec<&'a Expr>)> {
    let mut args: Vec<&Expr> = vec![arg];
    let mut cursor = func;
    loop {
        match cursor {
            Expr::App {
                func: inner_func,
                arg: inner_arg,
                ..
            } => {
                args.push(inner_arg);
                cursor = inner_func;
            }
            Expr::Var { name, .. } if is_upper(name) => {
                args.reverse();
                return Some((name.clone(), args));
            }
            _ => return None,
        }
    }
}

fn render_lambda(params: &[Pattern], body: &Expr, ctx: &ExprCtx) -> String {
    // Collect parameter names and track which patterns need
    // destructuring. Non-trivial patterns — anything other than a
    // plain `Var` or `Wildcard` — are bound to a fresh `_argN` name
    // and then destructured on entry to the body via `case _argN in
    // pat end`.
    //
    // An earlier version emitted `case ; in pat; end;` (no
    // scrutinee), which Ruby accepts syntactically but never actually
    // binds pattern variables, so later references to those names
    // raised `NameError`. The fix is to feed the real argument as
    // the scrutinee. This path is not exercised by M9 but is
    // required for e.g. `\(Just x) -> x` and is covered by tests
    // below. See must-fix item 2 on the I7 codegen review.
    let mut new_locals: Vec<String> = Vec::new();
    let mut param_names: Vec<String> = Vec::new();
    let mut destructure_indices: Vec<usize> = Vec::new();
    for (i, p) in params.iter().enumerate() {
        match p {
            Pattern::Var { name, .. } => {
                param_names.push(name.clone());
                new_locals.push(name.clone());
            }
            Pattern::Wildcard(_) => {
                param_names.push(format!("_arg{i}"));
            }
            _ => {
                // Generic: bind to a fresh name, then destructure at
                // the body's entry via case/in.
                let fresh = format!("_arg{i}");
                param_names.push(fresh);
                destructure_indices.push(i);
                // Pull every name bound by the pattern into the
                // local set so the body's references resolve to the
                // destructured bindings rather than escaping to the
                // prelude or to a global.
                for n in collect_binders(&params[i]) {
                    new_locals.push(n);
                }
            }
        }
    }
    let inner_ctx = ctx.with_locals(new_locals);

    let body_src = render_expr(body, &inner_ctx);
    let core = if destructure_indices.is_empty() {
        body_src
    } else {
        let mut s = String::new();
        for i in &destructure_indices {
            let fresh = &param_names[*i];
            let pat = render_pattern(&params[*i]);
            // `case <scrutinee>; in <pat>; end` binds any variables
            // named in `pat` into the enclosing Ruby scope. The
            // trailing `;` separates the destructure from the body
            // expression that follows.
            s.push_str(&format!("case {fresh}; in {pat}; end; "));
        }
        s.push_str(&body_src);
        s
    };

    // Curry: \x y -> b becomes ->(x) { ->(y) { b } }.
    let mut out = core;
    for p in param_names.iter().rev() {
        out = format!("->({p}) {{ {out} }}");
    }
    out
}

fn render_let(name: &str, value: &Expr, body: &Expr, ctx: &ExprCtx) -> String {
    // Sapphire `let x = e1 in e2` is recursive per spec 03. Emit an
    // IIFE with a forward-declared lambda slot to simulate recursion
    // without leaking the binding outside.
    let inner_ctx = ctx.with_local(name);
    let value_src = render_expr(value, &inner_ctx);
    let body_src = render_expr(body, &inner_ctx);
    format!("(lambda {{ {name} = ({value_src}); ({body_src}) }}).call")
}

fn render_case(scrutinee: &Expr, arms: &[CaseArm], ctx: &ExprCtx) -> String {
    let scrut = render_expr(scrutinee, ctx);
    let mut out = String::new();
    out.push_str("(case (");
    out.push_str(&scrut);
    out.push(')');
    for arm in arms {
        let pat = render_pattern(&arm.pattern);
        let bound = collect_binders(&arm.pattern);
        let inner_ctx = ctx.with_locals(bound);
        let body = render_expr(&arm.body, &inner_ctx);
        out.push_str("; in ");
        out.push_str(&pat);
        out.push_str("; (");
        out.push_str(&body);
        out.push(')');
    }
    // A final else branch — keeps Ruby from raising NoMatchingPatternError
    // silently on exhaustive matches that Ruby's exhaustiveness analysis
    // cannot see through. Exhaustiveness on the Sapphire side is I-OQ60.
    out.push_str("; else; raise 'non-exhaustive case'");
    out.push_str("; end)");
    out
}

fn collect_binders(p: &Pattern) -> Vec<String> {
    let mut out = Vec::new();
    collect_binders_rec(p, &mut out);
    out
}

fn collect_binders_rec(p: &Pattern, out: &mut Vec<String>) {
    match p {
        Pattern::Wildcard(_) | Pattern::Lit(_, _) => {}
        Pattern::Var { name, .. } => out.push(name.clone()),
        Pattern::As { name, inner, .. } => {
            out.push(name.clone());
            collect_binders_rec(inner, out);
        }
        Pattern::Con { args, .. } => {
            for a in args {
                collect_binders_rec(a, out);
            }
        }
        Pattern::Cons { head, tail, .. } => {
            collect_binders_rec(head, out);
            collect_binders_rec(tail, out);
        }
        Pattern::List { items, .. } => {
            for i in items {
                collect_binders_rec(i, out);
            }
        }
        Pattern::Record { fields, .. } => {
            for (_, pat) in fields {
                collect_binders_rec(pat, out);
            }
        }
        Pattern::Annot { inner, .. } => collect_binders_rec(inner, out),
    }
}

fn render_binop(op: &str, left: &Expr, right: &Expr, ctx: &ExprCtx) -> String {
    if op == "::" {
        return format!("[{}, *{}]", render_expr(left, ctx), render_expr(right, ctx));
    }
    if op == ">>=" {
        return format!(
            "Sapphire::Prelude.monad_bind(({}), ({}))",
            render_expr(left, ctx),
            render_expr(right, ctx)
        );
    }
    if op == ">>" {
        // `m >> n` discards the result of `m` but must **not** evaluate
        // `n` when `m` short-circuits (e.g. `Err _` in the Result
        // monad or a failed `Ruby` action). We thunk the RHS through a
        // zero-arg lambda; `monad_then` in the prelude calls it only
        // when the LHS would have continued.
        return format!(
            "Sapphire::Prelude.monad_then(({}), -> {{ ({}) }})",
            render_expr(left, ctx),
            render_expr(right, ctx)
        );
    }
    if let Some(ruby_op) = runtime::binop_inline(op) {
        return format!(
            "(({}) {} ({}))",
            render_expr(left, ctx),
            ruby_op,
            render_expr(right, ctx)
        );
    }
    // Fallback: look up the operator as a prelude value and call it
    // like any other curried function.
    let f = runtime::prelude_value(op).unwrap_or_else(|| format!("Sapphire::Prelude::{op}"));
    format!(
        "(({}).call({})).call({})",
        f,
        render_expr(left, ctx),
        render_expr(right, ctx)
    )
}

fn render_do(stmts: &[DoStmt], ctx: &ExprCtx) -> String {
    // Desugar do to >>= chains per spec 07 §do notation.
    let desugared = desugar_do(stmts);
    render_expr(&desugared, ctx)
}

/// Desugar a `do` statement list into a single `Expr` using `>>=`,
/// `>>`, and `let` bindings.
fn desugar_do(stmts: &[DoStmt]) -> Expr {
    desugar_do_rec(stmts)
}

fn desugar_do_rec(stmts: &[DoStmt]) -> Expr {
    assert!(!stmts.is_empty(), "empty do block");
    match &stmts[0] {
        DoStmt::Expr(e) if stmts.len() == 1 => e.clone(),
        DoStmt::Expr(e) => {
            let rest = desugar_do_rec(&stmts[1..]);
            // e >> rest
            Expr::BinOp {
                op: ">>".into(),
                left: Box::new(e.clone()),
                right: Box::new(rest),
                span: Span::empty(0),
            }
        }
        DoStmt::Bind { pattern, expr, .. } => {
            let rest = desugar_do_rec(&stmts[1..]);
            // e >>= \pat -> rest
            let lambda = Expr::Lambda {
                params: vec![pattern.clone()],
                body: Box::new(rest),
                span: Span::empty(0),
            };
            Expr::BinOp {
                op: ">>=".into(),
                left: Box::new(expr.clone()),
                right: Box::new(lambda),
                span: Span::empty(0),
            }
        }
        DoStmt::Let {
            name,
            value,
            params,
            ..
        } if stmts.len() == 1 => {
            // `let x = e` as a trailing stmt: emit `let x = e in e`
            // which evaluates to `e` — degenerate, but legal.
            let value_expr = if params.is_empty() {
                value.clone()
            } else {
                Expr::Lambda {
                    params: params.clone(),
                    body: Box::new(value.clone()),
                    span: Span::empty(0),
                }
            };
            Expr::Let {
                name: name.clone(),
                operator: false,
                params: vec![],
                value: Box::new(value_expr.clone()),
                body: Box::new(value_expr),
                span: Span::empty(0),
            }
        }
        DoStmt::Let {
            name,
            value,
            params,
            ..
        } => {
            let rest = desugar_do_rec(&stmts[1..]);
            let value_expr = if params.is_empty() {
                value.clone()
            } else {
                Expr::Lambda {
                    params: params.clone(),
                    body: Box::new(value.clone()),
                    span: Span::empty(0),
                }
            };
            Expr::Let {
                name: name.clone(),
                operator: false,
                params: vec![],
                value: Box::new(value_expr),
                body: Box::new(rest),
                span: Span::empty(0),
            }
        }
    }
}

/// Ruby module path from a Sapphire module's segments. `Foo.Bar` →
/// `Sapphire::Foo::Bar` for multi-segment names; the single-segment
/// case `Foo` → `Sapphire::Foo`. The special `Prelude` module maps
/// to `Sapphire::Prelude`.
pub fn ruby_module_path(segments: &[String]) -> String {
    let mut out = String::from("Sapphire");
    for seg in segments {
        out.push_str("::");
        out.push_str(seg);
    }
    out
}

fn is_upper(name: &str) -> bool {
    name.chars().next().is_some_and(|c| c.is_ascii_uppercase())
}
